//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public System.Guid ItemID { get; set; }
        public int CartID { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string ItemDes { get; set; }
        public string ItemImg { get; set; }
        public decimal ItemPrice { get; set; }
    }
}
